name: Build Android APK

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Release APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.5'  # Or latest stable

      - name: Install dependencies
        run: flutter pub get

      - name: Build release APK
        run: flutter build apk --release --no-shrink

      - name: Upload APK artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: sidegig_ph-release.apk
          path: build/app/outputs/flutter-apk/app-release.apk
